version: '3.4'

services:

  development:
    build:
      context: .
      dockerfile: ./env/Dockerfile
    image: development
    ports:
    - "8888:8888"
    - "5678:5678"
    volumes:
    - ./env:/app/env
    - ./emlopt:/app/emlopt
    - ./tests:/app/tests
    - ./experiments:/app/experiments
