on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_all_job:
    runs-on: ubuntu-latest
    name: Run all tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build docker
        run: docker-compose build

      - name: Run tests
        run: docker-compose run development tests
